apiVersion: v1
kind: Service
metadata:
  name: myloadbalancer
  labels:
    app: embedding-py
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      name: http
      targetPort: 8080
  selector:
    app: embedding-py